name: Deploy PR to Preview Channel

on:
  pull_request:

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.FIREBASE_GITHUB_TOKEN }}"
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PERSONAL_WEBSITE_ASJORDI }}'
          expires: 30d
          projectId: "${{ secrets.FIREBASE_PROJECT_ID }}"
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
      - name: Create a comment with the preview URL
        if: success() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        env:
          MESSAGE_BODY: "Preview for this PR in ${{ inputs.environment }} is available at ${{ steps.firebase-deploy-preview.outputs.details_url }}"
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.MESSAGE_BODY
            });